# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteApp', '0002_auto_20190222_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='auth',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
